In [3]:
# Versão Python 
from platform import python_version
print("Versão da Linguagem Python usada neste Jupyter Notebook: ", python_version())

Versão da Linguagem Python usada neste Jupyter Notebook:  3.9.13


In [ ]:
# Para Instalar a versão exata de um pacote
!pip install numpy==1.21.3

# Para atualizar um pacote na versão mais recete
# !pip install -U nome_pacote

In [4]:
# Intalar o pcacote watermark
# Esse pacote é usado para gravar as versões de outros pcacotes usadados neste jupyter notebook.
!pip install -q -U watermark

In [5]:
# Importando o módulo NumPy
import numpy as np

In [13]:
# Versões dos pacotes usados neste jupyter notebook
%reload_ext watermark
%watermark -a "Data Science Academy" --iversions

Author: Data Science Academy

numpy: 1.21.3






ESTRUTURAS DE DADOS NUMPY

np.array([..]) 
função que permite criar uma array utilizando o NumPy

array.ndim
Verifica o número de dimensão

array.shape
Verifica o formato do array (4,) ou (2,3)

In [15]:
# Criando uma array unidimensional e passando para o NumPy
array1 = np.array([10,20,30,40])

In [16]:
print(array1)

[10 20 30 40]


In [17]:
# Verifica o formagto (shape) do array
array1.shape 
# (4,) indica que possui uma array de uma dimensão com 4 elementos

(4,)

In [18]:
# Verifica o número de dimensões
array1.ndim

1

In [20]:
# Criando array bi-dimensional
array2 = np.array([[100, 83, 15],[42, 78, 0]])

In [21]:
print(array2)

[[100  83  15]
 [ 42  78   0]]


In [23]:
array2.shape
# (2, 3)
# informa que possui duas dimensões com 3 elementos

(2, 3)

In [25]:
array2.ndim

2

ESTRURURAS DE DADOS COM ARANGE

np.arange([..])  
Função que criar uma array com o número de elementos que for passado como parâmetro



In [27]:
array3 = np.arange(15)

In [28]:
array3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [30]:
# Usando start/end 
array4 = np.arange(0, 15, 3)
# 0 é o valor inicial
# 15 é o valor final
# 3 é o número de saltos

In [31]:
array4 # (4,) ou (2,3)

array([ 0,  3,  6,  9, 12])

ESTRUTURAS DE DADOS COM LINSPACE

np.linspace([ ]): array
Fubção que criar um espaço linear para os valores que tiver no array

In [35]:
array5 = np.linspace(0, 3, 4)

In [36]:
array5 # array([0., 1., 2., 3.])

array([0., 1., 2., 3.])

ESTRUTURAS DE DADOS COM OUTRAS FUNÇÕES

numpy.zeros (arrays preenchidos com 0)

numpy.ones (arrays preenchidos com 1)

numpy.eye (arrays com matriz identidade 1 e 0)

numpy.diag (arrays com matriz diagona)

numpy.random.rand (preenchidos com valores aleatórios)

numpy.empty (preenchimento vazio)

numpy.tile (duplicando uma array)


In [38]:
array6 = np.zeros((10, 8)); array6
# array([[0., 0., 0., 0., 0., 0., 0., 0.],
 #      [0., 0., 0., 0., 0., 0., 0., 0.],
 #      [0., 0., 0., 0., 0., 0., 0., 0.],
 #      [0., 0., 0., 0., 0., 0., 0., 0.],
 #      [0., 0., 0., 0., 0., 0., 0., 0.],
 #      [0., 0., 0., 0., 0., 0., 0., 0.],
 #      [0., 0., 0., 0., 0., 0., 0., 0.],
 #      [0., 0., 0., 0., 0., 0., 0., 0.],
 #      [0., 0., 0., 0., 0., 0., 0., 0.],
 #      [0., 0., 0., 0., 0., 0., 0., 0.]])

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [39]:
array7 = np.ones((2, 3, 2)); array7
# array([[[1., 1.],
#        [1., 1.],
#        [1., 1.]],

#       [[1., 1.],
#        [1., 1.],
#        [1., 1.]]])

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [40]:
array8 = np.eye(3); array8
# array([[1., 0., 0.],
#       [0., 1., 0.],
#       [0., 0., 1.]])

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [41]:
array9 = np.diag((2, 1, 4, 6)); array9
#array([[2, 0, 0, 0],
#       [0, 1, 0, 0],
#       [0, 0, 4, 0],
#       [0, 0, 0, 6]])

array([[2, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 6]])

In [43]:
# Função rand(n) produz uma sequencia de números uniformemente distriobuidos com range de 0 a n
np.random.seed(100) # set seed
array10 = np.random.rand(5); array10
# array([0.54340494, 0.27836939, 0.42451759, 0.84477613, 0.00471886])

array([0.54340494, 0.27836939, 0.42451759, 0.84477613, 0.00471886])

In [44]:
# produz uma sequencia de números com distribuição normal (Gaussian)
array11 = np.random.randn(5); array11
# array([ 0.35467445, -0.78606433, -0.2318722 ,  0.20797568,  0.93580797])

array([ 0.35467445, -0.78606433, -0.2318722 ,  0.20797568,  0.93580797])

In [45]:
array12 = np.empty((3, 2)); array12
#array([[6.23042070e-307, 4.67296746e-307],
#       [1.69121096e-306, 8.45599366e-307],
#       [6.23057349e-307, 2.22526399e-307]])

array([[6.23042070e-307, 4.67296746e-307],
       [1.69121096e-306, 8.45599366e-307],
       [6.23057349e-307, 2.22526399e-307]])

In [47]:
np.array([[9, 4],[3, 7]])

array([[9, 4],
       [3, 7]])

In [49]:
# Duplicando a array
np.tile(np.array([[9, 4], [3, 7]]), 4)
#array([[9, 4, 9, 4, 9, 4, 9, 4],
#       [3, 7, 3, 7, 3, 7, 3, 7]])

array([[9, 4, 9, 4, 9, 4, 9, 4],
       [3, 7, 3, 7, 3, 7, 3, 7]])

In [50]:
# Duplicando a array
np.tile(np.array([[9, 4], [3, 7]]), (2,2))
#array([[9, 4, 9, 4],
#       [3, 7, 3, 7],
#       [9, 4, 9, 4],
#       [3, 7, 3, 7]])

array([[9, 4, 9, 4],
       [3, 7, 3, 7],
       [9, 4, 9, 4],
       [3, 7, 3, 7]])

TIPOS DE DADOS NUMPY

Declando o tipo da array

In [56]:
array13 = np.array([8, -3, 5, 9], dtype = "float")

In [57]:
print(array13)

[ 8. -3.  5.  9.]


In [58]:
array13.dtype # dtype('float64')


dtype('float64')

In [59]:
array14 = np.array([2, 4, 6, 8])

In [60]:
array14.dtype # dtype('int32')


dtype('int32')

In [61]:
array15 = np.array([2.0, 4, 6, 8])

In [62]:
array15.dtype # dtype('float64')


dtype('float64')

In [63]:
array16 = np.array(["Data", "Science", "Academy"])

In [64]:
array16.dtype # dtype('<U7') unicode


dtype('<U7')

In [66]:
array17 = np.array([True, False, True])

In [67]:
array17.dtype # dtype('bool')

dtype('bool')

In [68]:
array18 = np.array([7, -3, 5.24])

In [69]:
array18.dtype # dtype('float64')

dtype('float64')

In [71]:
#Converte os elementos da array
array18.astype(int) # array([ 7, -3,  5])

array([ 7, -3,  5])

dtype('float64')

OPERAÇÕES COM ARRAYS

In [73]:
# Array começando por 0, com 30 elementos e multiplicando por 5
array19 = np.arange(0, 10) * 5

In [74]:
array19 # array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [75]:
#Elevando um array a quarta potência
array20 = np.arange(5) **4 

In [76]:
array20 # array([  0,   1,  16,  81, 256], dtype=int32)

array([  0,   1,  16,  81, 256], dtype=int32)

In [77]:
# Somando um número a cada elemento do array
array21 = np.arange(0, 30) + 1

In [78]:
array21
#array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
#       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [85]:
array22 = np.arange(0, 30, 3) + 3
array23 = np.arange(1, 11)

In [86]:
array22 #array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [87]:
array23 #array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [88]:
array22 - array23 #array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [89]:
array22 + array23 #array([ 4,  8, 12, 16, 20, 24, 28, 32, 36, 40])

array([ 4,  8, 12, 16, 20, 24, 28, 32, 36, 40])

In [90]:
array22 * array23 #array([  3,  12,  27,  48,  75, 108, 147, 192, 243, 300])

array([  3,  12,  27,  48,  75, 108, 147, 192, 243, 300])

In [91]:
array22 / array23 #array([3., 3., 3., 3., 3., 3., 3., 3., 3., 3.])

array([3., 3., 3., 3., 3., 3., 3., 3., 3., 3.])

In [92]:
array22 > array23 #array([ True,  True,  True,  True,  True,  True,  True,  True,  True, True])

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [94]:
arr1 = np.array([True, False, True, False])
arr2 = np.array([False, False, True, False])

In [95]:
# Função que verifica se cada elementos da arrays são identicas
np.logical_and(arr1, arr2)

array([False, False,  True, False])